#!/usr/bin/env python3
"""Generate the ROS-flavored URDF twins (``*_ros.urdf``) from their base URDFs.

The base URDFs in this directory (e.g. ``h1_2_magpie.urdf``) are the single
source of truth: they use relative mesh paths (``../meshes/...``) and an
articulated gripper, and are consumed by Pinocchio / the IK controller. The
``*_ros.urdf`` twins are a *pure function* of the base and are consumed by
``robot_state_publisher`` / RViz. They differ only by:

  1. mesh paths rewritten to ``package://h12_ros2_model/...`` URIs (so RViz /
     ``robot_state_publisher`` resolve meshes through the ROS package), and
  2. the 12 magpie finger hinge joints rigidified to ``type="fixed"``. Those
     joints have no ``/joint_states`` source (``NUM_HAND_DOF = 0``), so as
     ``revolute``/``continuous`` joints ``robot_state_publisher`` never emits
     their TF and the gripper links silently vanish in RViz; fixed joints render
     them at rest via ``/tf_static`` (viz-only override; the base stays
     articulated for Pinocchio/sim).

Run it in place after editing any base URDF::

    cd CL_Assets/ros_assets && python3 gen_ros_urdf.py            # regenerate
    cd CL_Assets/ros_assets && python3 gen_ros_urdf.py --check    # CI / dry-run

``core_ws/src/h12_ros2_model/setup.py`` imports the transform from this module
and fails the colcon build if a committed ``*_ros.urdf`` is stale, so the twins
can never silently drift. Importing this module has no side effects (the CLI is
guarded by ``__main__``); stdlib only, so it is safe to import during the build.
"""

import argparse
import os
import re
import sys
from xml.parsers import expat

# (base, ros) twins this generator owns. Add a tuple to cover a new twin.
PAIRS = [
    ("h1_2_magpie.urdf", "h1_2_magpie_ros.urdf"),
    ("h1_2_handless.urdf", "h1_2_handless_ros.urdf"),
]

# package:// prefix for the installed h12_ros2_model share layout, where h1_2
# body meshes sit directly under assets/h1_2/meshes/ and gripper meshes under
# assets/h1_2/meshes/magpie/ (see h12_ros2_model/setup.py data_files).
PKG_BASE = "package://h12_ros2_model/assets/h1_2/"

# The 12 magpie finger hinge joints: articulated in the base, rigidified (fixed)
# in the _ros twin so robot_state_publisher renders the gripper without needing
# /joint_states for them. See module docstring.
_HINGE_JOINT = re.compile(
    r'(<joint name="(?:rg|lg)_(?:left|right)_hinge_[123]") type="[^"]*"(.*?)</joint>',
    re.S,
)

_HEADER_PREFIX = "<!-- AUTOGENERATED"
# NOTE: an XML comment must NOT contain a double hyphen ('--'); keep this string
# free of '--' or strict parsers (libxml2/expat, used by RViz / rclpy tooling)
# will reject the whole URDF. generate() re-validates well-formedness as a guard.
_HEADER_FMT = (
    "<!-- AUTOGENERATED from {base} by CL_Assets/ros_assets/gen_ros_urdf.py. "
    "DO NOT EDIT; regenerate after editing {base}. -->"
)


def rewrite_mesh_package(text):
    """Rewrite base relative mesh paths to package:// URIs."""
    text = text.replace("../meshes/h1_2/", PKG_BASE + "meshes/")
    text = text.replace("../meshes/magpie/", PKG_BASE + "meshes/magpie/")
    return text


def rewrite_mesh_share_relative(text):
    """Rewrite base relative mesh paths to the share-layout relative form.

    This is the rewrite h12_ros2_model/setup.py applies when staging the
    Pinocchio-flavor (non-_ros) URDFs; kept here so the mesh-dir rules live in a
    single place.
    """
    text = text.replace("../meshes/h1_2/", "meshes/")
    text = text.replace("../meshes/magpie/", "meshes/magpie/")
    return text


def rigidify_gripper(text):
    """Set the magpie finger hinge joints to fixed (strip axis/limit).

    No-op on URDFs without those joints (e.g. handless).
    """

    def repl(m):
        body = re.sub(r"\s*<axis[^>]*/>", "", m.group(2))
        body = re.sub(r"\s*<limit[^>]*/>", "", body)
        return '{0} type="fixed"{1}</joint>'.format(m.group(1), body)

    return _HINGE_JOINT.sub(repl, text)


def base_to_ros(text):
    """The full base -> _ros body transform (no header)."""
    return rigidify_gripper(rewrite_mesh_package(text))


def strip_header(text):
    """Remove a leading AUTOGENERATED comment line, if present."""
    if text.startswith(_HEADER_PREFIX):
        end = text.find("-->")
        if end != -1:
            rest = text[end + 3:]
            if rest.startswith("\n"):
                rest = rest[1:]
            return rest
    return text


def add_header(body, base):
    """Prepend the AUTOGENERATED header (idempotent)."""
    return _HEADER_FMT.format(base=base) + "\n" + strip_header(body)


def assert_well_formed(text, label):
    """Raise ValueError unless `text` is well-formed XML (strict, expat).

    check_urdf / TinyXML are lenient (e.g. they tolerate '--' inside comments),
    but RViz's model loader and Python (libxml2/expat) tooling are strict, so we
    validate with expat to match what actually consumes the URDF at runtime.
    """
    p = expat.ParserCreate()
    try:
        p.Parse(text, True)
    except expat.ExpatError as e:
        raise ValueError("{0} is not well-formed XML: {1}".format(label, e))


def expected_ros(base_text, base_name):
    """Full expected _ros file content (with header) for a base file."""
    out = add_header(base_to_ros(base_text), base_name)
    assert_well_formed(out, base_name + " -> _ros")
    return out


def _first_diff_line(a, b):
    """1-based index + the two lines at the first difference, for messages."""
    al, bl = a.splitlines(), b.splitlines()
    for i, (x, y) in enumerate(zip(al, bl)):
        if x != y:
            return i + 1, x, y
    if len(al) != len(bl):
        n = min(len(al), len(bl))
        extra = (al[n:] or bl[n:])[:1]
        return n + 1, "".join(al[n:n + 1]), "".join(bl[n:n + 1]) or (extra[0] if extra else "")
    return None


def stale_reason(base_text, ros_text):
    """Return None if ros_text is in sync with base_text, else a message.

    Compares bodies (header stripped), so a header-only difference does not
    count as drift.
    """
    want = base_to_ros(base_text)
    have = strip_header(ros_text)
    if want == have:
        return None
    d = _first_diff_line(have, want)
    if d is None:
        return "content differs"
    ln, got, exp = d
    return (
        "first mismatch at body line {0}:\n"
        "    committed: {1}\n"
        "    expected : {2}".format(ln, got.strip()[:200], exp.strip()[:200])
    )


def check_pairs(assets_dir):
    """Return list of (ros_name, reason) for every stale/missing twin."""
    problems = []
    for base_name, ros_name in PAIRS:
        base_path = os.path.join(assets_dir, base_name)
        ros_path = os.path.join(assets_dir, ros_name)
        with open(base_path, "r") as f:
            base_text = f.read()
        if not os.path.exists(ros_path):
            problems.append((ros_name, "missing (run gen_ros_urdf.py)"))
            continue
        with open(ros_path, "r") as f:
            ros_text = f.read()
        try:
            assert_well_formed(ros_text, ros_name)
        except ValueError as e:
            problems.append((ros_name, str(e)))
            continue
        reason = stale_reason(base_text, ros_text)
        if reason is not None:
            problems.append((ros_name, reason))
    return problems


def generate(assets_dir, dry_run=False):
    """Write each _ros twin; return list of names that changed."""
    changed = []
    for base_name, ros_name in PAIRS:
        base_path = os.path.join(assets_dir, base_name)
        ros_path = os.path.join(assets_dir, ros_name)
        with open(base_path, "r") as f:
            base_text = f.read()
        want = expected_ros(base_text, base_name)
        have = None
        if os.path.exists(ros_path):
            with open(ros_path, "r") as f:
                have = f.read()
        if have == want:
            continue
        changed.append(ros_name)
        if not dry_run:
            with open(ros_path, "w") as f:
                f.write(want)
    return changed


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--assets-dir",
        default=os.path.dirname(os.path.abspath(__file__)),
        help="directory holding the base + _ros URDFs (default: this script's dir)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="dry-run: exit nonzero if any _ros twin is stale (CI / pre-commit)",
    )
    args = parser.parse_args(argv)

    if args.check:
        problems = check_pairs(args.assets_dir)
        if problems:
            print("STALE *_ros.urdf twins (regenerate with gen_ros_urdf.py):", file=sys.stderr)
            for name, reason in problems:
                print("  {0}: {1}".format(name, reason), file=sys.stderr)
            return 1
        print("OK: all *_ros.urdf twins are in sync with their base URDFs.")
        return 0

    changed = generate(args.assets_dir)
    if changed:
        print("Regenerated: " + ", ".join(changed))
    else:
        print("Up to date: no changes.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
